// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package drcBible

import (
	"database/sql"
)

type CrossReference struct {
	ID           int64
	FromBook     sql.NullString
	FromChapter  sql.NullInt64
	FromVerse    sql.NullInt64
	ToBook       sql.NullString
	ToChapter    sql.NullInt64
	ToVerseStart sql.NullInt64
	ToVerseEnd   sql.NullInt64
	Votes        sql.NullInt64
}

type DrcBook struct {
	ID   int64
	Name sql.NullString
}

type DrcVerse struct {
	ID      int64
	BookID  sql.NullInt64
	Chapter sql.NullInt64
	Verse   sql.NullInt64
	Text    sql.NullString
}
