// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {reference} from '../models';

export function GetAllBooks():Promise<Array<services.BookResponse>>;

export function GetAllChapters(arg1:number):Promise<Array<number>>;

export function SearchVerse(arg1:string):Promise<reference.BibleReference>;
