// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reference} from '../models';

export function SearchVerse(arg1:string):Promise<reference.BibleReference>;
