// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllBooks() {
  return window['go']['main']['App']['GetAllBooks']();
}

export function GetAllChapters(arg1) {
  return window['go']['main']['App']['GetAllChapters'](arg1);
}

export function SearchVerse(arg1) {
  return window['go']['main']['App']['SearchVerse'](arg1);
}
